% Facts (59 parent edges)
parent(alice, bob).
parent(bob, laura).
parent(laura, jack).
parent(jack, peter).
parent(peter, dora).
parent(dora, emma).
parent(emma, frank).
parent(frank, george).
parent(george, helen).
parent(helen, irene).
parent(irene, john).
parent(john, kate).
parent(kate, leo).
parent(leo, maria).
parent(maria, nathan).
parent(nathan, olivia).
parent(olivia, paul).
parent(paul, quinn).
parent(quinn, rachel).
parent(rachel, sam).
parent(sam, tina).
parent(tina, ursula).
parent(ursula, victor).
parent(victor, wendy).
parent(wendy, xavier).
parent(xavier, yvonne).
parent(yvonne, zach).
parent(zach, adam).
parent(adam, bella).
parent(bella, charlie).
parent(charlie, daniel).
parent(daniel, evelyn).
parent(evelyn, felix).
parent(felix, grace).
parent(grace, henry).
parent(henry, isabel).
parent(isabel, julian).
parent(julian, karen).
parent(karen, liam).
parent(liam, monica).
parent(monica, noah).
parent(noah, ophelia).
parent(ophelia, patrick).
parent(patrick, queenie).
parent(queenie, robert).
parent(robert, sophia).
parent(sophia, thomas).
parent(thomas, una).
parent(una, vincent).
parent(vincent, willow).
parent(willow, xena).
parent(xena, yuri).
parent(yuri, zoe).
parent(zoe, alan).
parent(alan, bianca).
parent(bianca, caleb).
parent(caleb, daphne).
parent(daphne, elijah).
parent(elijah, freya).   