% Facts (30 parent edges)
parent(alice, bob).
parent(bob, laura).
parent(laura, jack).
parent(jack, peter).
parent(peter, dora).
parent(dora, emma).
parent(emma, frank).
parent(frank, george).
parent(george, helen).
parent(helen, irene).
parent(irene, john).
parent(john, kate).
parent(kate, leo).
parent(leo, maria).
parent(maria, nathan).
parent(nathan, olivia).
parent(olivia, paul).
parent(paul, quinn).
parent(quinn, rachel).
parent(rachel, sam).
parent(sam, tina).
parent(tina, ursula).
parent(ursula, victor).
parent(victor, wendy).
parent(wendy, xavier).
parent(xavier, yvonne).
parent(yvonne, zach).
parent(zach, adam).
parent(adam, bella).
parent(bella, charlie).