% Facts
tr1(alice, bob).
tr2(alice, bob).
tr3(alice, bob).
tr4(alice, bob).
tr5(alice, bob).
tr6(alice, bob).
tr7(alice, bob).
tr8(alice, bob).
tr9(alice, bob).
tr10(alice, bob).
tr11(alice, bob).
tr12(alice, bob).
tr13(alice, bob).
tr14(alice, bob).
tr15(alice, bob).
tr16(alice, bob).
tr17(alice, bob).
tr18(alice, bob).
tr19(alice, bob).
tr20(alice, bob).
tr21(alice, bob).
tr22(alice, bob).
tr23(alice, bob).
tr24(alice, bob).