[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-groth16 = { workspace = true }
ark-bn254 = { workspace = true, features = ["curve"] }
serde = { workspace = true }
ark-snark = { workspace = true }
ark-serialize = { workspace = true }
base64 = { workspace = true, features = ["alloc"] }
serde_json = { workspace = true, features = ["std"] }
anyhow = { workspace = true } 