[package]
name = "verify"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
anyhow = { workspace = true }
ark-groth16 = { workspace = true }
ark-bn254 = { workspace = true }
ark-snark = { workspace = true }